#ifndef APP_INFO_DISPLAY_NAME
#include "../../info.c"
#endif

#ifndef LOCK_FILE_PATH
#define LOCK_FILE_PATH "/tmp/" APP_INFO_PACKAGE_NAME ".lock"
#endif

#ifndef MINIMUM_REFRESH_TIME_IN_SECONDS
#define MINIMUM_REFRESH_TIME_IN_SECONDS 2
#endif

#ifndef IS_BRIGHTNESS_LINKED_GSETTINGS_KEY
#define IS_BRIGHTNESS_LINKED_GSETTINGS_KEY "is-brightness-linked"
#endif

#ifndef IS_BRIGHTNESS_PROPORTIONALLY_LINKED_GSETTINGS_KEY
#define IS_BRIGHTNESS_PROPORTIONALLY_LINKED_GSETTINGS_KEY "is-brightness-proportionally-linked"
#endif

#ifndef SHOULD_HIDE_INTERNAL_IF_LID_CLOSED_GSETTINGS_KEY
#define SHOULD_HIDE_INTERNAL_IF_LID_CLOSED_GSETTINGS_KEY "should-hide-internal-if-lid-closed"
#endif

#ifndef MAX_BRIGHTNESS_PER_DISPLAY_GSETTINGS_KEY
#define MAX_BRIGHTNESS_PER_DISPLAY_GSETTINGS_KEY "max-brightness-per-display"
#endif

#ifndef MIN_BRIGHTNESS_PER_DISPLAY_GSETTINGS_KEY
#define MIN_BRIGHTNESS_PER_DISPLAY_GSETTINGS_KEY "min-brightness-per-display"
#endif
